Traceback (most recent call last):
  File "/home/kalyan/gitrepo/alma-mater/Sem4/ICN/Quiz/client.py", line 27, in <module>
    client()
  File "/home/kalyan/gitrepo/alma-mater/Sem4/ICN/Quiz/client.py", line 11, in client
    client_socket.connect((host, port))  # connect to the server
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused
